/**
 * 基础数据
 */

export type BaseCategory = {
  id: string
  name: string
  description: string
  icon: string
  components: string[]
}

export type BaseProp = {
  name: string
  type: string
  description: string
  required: boolean
  default: any
  options?: string[]
}

export type BaseComponentMeta = {
  id: string
  title: string
  description: string
  category: string
  version: string
  props: BaseProp[]
  keywords: string[]
  aliases: string[]
  difficulty: string
  popularity: number
}

// 分类数据（来自 categories.json）
export const baseCategories: BaseCategory[] = [
  {
    id: 'navigation',
    name: '导航',
    description: '页面导航和菜单相关组件',
    icon: 'navigation',
    components: ['navbar', 'tabbar', 'tabs', 'steps', 'sticky'],
  },
  {
    id: 'form',
    name: '表单',
    description: '表单输入和选择相关组件',
    icon: 'form',
    components: [
      'button',
      'input',
      'checkbox',
      'radio',
      'picker',
      'slider',
      'switch',
      'form',
      'number-box',
      'search-box',
      'keyboard',
      'form-item',
    ],
  },
  {
    id: 'feedback',
    name: '反馈',
    description: '用户反馈和提示相关组件',
    icon: 'feedback',
    components: [
      'action-sheet',
      'modal',
      'popup',
      'loading',
      'notify',
      'badge',
      'line-progress',
      'circle-progress',
      'loadmore',
    ],
  },
  {
    id: 'display',
    name: '展示',
    description: '内容展示和显示相关组件',
    icon: 'display',
    components: [
      'avatar',
      'image-upload',
      'icon',
      'tag',
      'empty',
      'footer',
      'title',
      'read-more',
      'photo-album',
      'water-fall',
    ],
  },
  {
    id: 'container',
    name: '容器',
    description: '容器和布局相关组件',
    icon: 'container',
    components: [
      'collapse',
      'sticky',
      'swiper',
      'popup',
      'overlay',
      'list',
      'scroll-list',
      'index-list',
    ],
  },
  {
    id: 'business',
    name: '业务',
    description: '特定业务场景组件',
    icon: 'business',
    components: [
      'calendar',
      'count-down',
      'count-scroll',
      'count-to',
      'image-upload',
      'region-picker',
      'date-time-picker',
      'week-calendar',
      'bubble-box',
      'rate',
    ],
  },
  {
    id: 'other',
    name: '其他',
    description: '其他辅助组件',
    icon: 'other',
    components: [
      'notice-bar',
      'column-notice-bar',
      'row-notice-bar',
      'lazy-load',
      'subsection',
      'switch-tab',
      'swipe-action',
    ],
  },
]

// 组件元数据 - 基于图鸟JSON整理
export const baseComponents: BaseComponentMeta[] = [
  // 导航分类
  {
    id: 'navbar',
    title: '导航栏',
    description: '页面导航栏组件',
    category: 'navigation',
    version: '1.0.0',
    keywords: ['导航', '导航栏', '标题栏'],
    aliases: ['导航栏'],
    difficulty: 'beginner',
    popularity: 9,
    props: [
      {
        name: 'title',
        type: 'string',
        description: '导航栏标题',
        required: false,
        default: '',
      },
      {
        name: 'fixed',
        type: 'boolean',
        description: '是否固定顶部',
        required: false,
        default: true,
      },
      {
        name: 'bgColor',
        type: 'string',
        description: '背景颜色',
        required: false,
        default: null,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: 'transparent',
          color: '#333333',
          fontSize: '16px',
          padding: '0',
          margin: '0',
          width: '100%',
          height: 'auto',
        },
      },
    ],
  },
  {
    id: 'tabbar',
    title: '标签栏',
    description: '底部标签导航栏组件',
    category: 'navigation',
    version: '1.0.0',
    keywords: ['底部', '标签', '导航'],
    aliases: ['标签栏'],
    difficulty: 'beginner',
    popularity: 10,
    props: [
      {
        name: 'active',
        type: 'number',
        description: '当前激活项索引',
        required: false,
        default: 0,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#ffffff',
          color: '#333333',
          fontSize: '12px',
          padding: '0',
          margin: '0',
          width: '100%',
          height: 'auto',
          borderTopColor: '#e5e7eb',
          borderTopWidth: '1px',
        },
      },
    ],
  },
  {
    id: 'steps',
    title: '步骤条',
    description: '步骤展示组件',
    category: 'navigation',
    version: '1.0.0',
    keywords: ['步骤', '流程'],
    aliases: ['步骤条'],
    difficulty: 'intermediate',
    popularity: 7,
    props: [
      {
        name: 'active',
        type: 'number',
        description: '当前激活步骤',
        required: false,
        default: 0,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: 'transparent',
          color: '#333333',
          fontSize: '14px',
          padding: '0',
          margin: '0',
          width: 'auto',
          height: 'auto',
        },
      },
    ],
  },
  // 表单分类
  {
    id: 'button',
    title: '按钮',
    description: '按钮组件，用于触发操作',
    category: 'form',
    version: '1.0.0',
    keywords: ['按钮', '点击', '操作'],
    aliases: ['按钮'],
    difficulty: 'beginner',
    popularity: 10,
    props: [
      {
        name: 'text',
        type: 'string',
        description: '按钮文字',
        required: false,
        default: '按钮',
      },
      {
        name: 'type',
        type: 'string',
        description: '按钮类型',
        required: false,
        default: 'primary',
        options: ['primary', 'success', 'warning', 'danger', 'info'],
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: '是否禁用',
        required: false,
        default: false,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#3b82f6',
          color: '#ffffff',
          fontSize: '16px',
          padding: '8px 16px',
          margin: '0',
          borderRadius: '4px',
          borderColor: '#3b82f6',
          borderWidth: '1px',
          borderStyle: 'solid',
          width: 'auto',
          height: 'auto',
        },
      },
    ],
  },
  {
    id: 'input',
    title: '输入框',
    description: '文本输入框组件',
    category: 'form',
    version: '1.0.0',
    keywords: ['输入', '文本框', '表单'],
    aliases: ['输入框'],
    difficulty: 'beginner',
    popularity: 10,
    props: [
      {
        name: 'placeholder',
        type: 'string',
        description: '占位提示文字',
        required: false,
        default: '请输入内容',
      },
      {
        name: 'value',
        type: 'string',
        description: '输入框值',
        required: false,
        default: '',
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: '是否禁用',
        required: false,
        default: false,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#ffffff',
          color: '#333333',
          fontSize: '16px',
          width: '200px',
          height: 'auto',
          padding: '8px 12px',
          margin: '0',
          borderRadius: '4px',
          borderColor: '#dddddd',
          borderWidth: '1px',
          borderStyle: 'solid',
        },
      },
    ],
  },
  {
    id: 'checkbox',
    title: '复选框',
    description: '多选框组件，支持多选和单选',
    category: 'form',
    version: '1.0.0',
    keywords: ['复选框', '多选', '选择'],
    aliases: ['复选框', '多选框'],
    difficulty: 'beginner',
    popularity: 8,
    props: [
      {
        name: 'checked',
        type: 'boolean',
        description: '是否选中',
        required: false,
        default: false,
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: '是否禁用',
        required: false,
        default: false,
      },
      {
        name: 'label',
        type: 'string',
        description: '复选框文字',
        required: false,
        default: '',
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          color: '#333333',
          fontSize: '14px',
          padding: '0',
          margin: '0',
          width: 'auto',
          height: 'auto',
        },
      },
    ],
  },
  {
    id: 'radio',
    title: '单选框',
    description: '单选框组件',
    category: 'form',
    version: '1.0.0',
    keywords: ['单选', '选择'],
    aliases: ['单选框'],
    difficulty: 'beginner',
    popularity: 8,
    props: [
      {
        name: 'checked',
        type: 'boolean',
        description: '是否选中',
        required: false,
        default: false,
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: '是否禁用',
        required: false,
        default: false,
      },
      {
        name: 'label',
        type: 'string',
        description: '单选框文字',
        required: false,
        default: '',
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          color: '#333333',
          fontSize: '14px',
          padding: '0',
          margin: '0',
          width: 'auto',
          height: 'auto',
        },
      },
    ],
  },
  {
    id: 'slider',
    title: '滑块',
    description: '滑块选择组件',
    category: 'form',
    version: '1.0.0',
    keywords: ['滑块', '滑动', '选择'],
    aliases: ['滑块'],
    difficulty: 'beginner',
    popularity: 7,
    props: [
      {
        name: 'value',
        type: 'number',
        description: '当前值',
        required: false,
        default: 0,
      },
      {
        name: 'min',
        type: 'number',
        description: '最小值',
        required: false,
        default: 0,
      },
      {
        name: 'max',
        type: 'number',
        description: '最大值',
        required: false,
        default: 100,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#e5e7eb',
          color: '#3b82f6',
          width: '200px',
          height: 'auto',
          padding: '0',
          margin: '0',
        },
      },
    ],
  },
  {
    id: 'switch',
    title: '开关',
    description: '开关选择组件',
    category: 'form',
    version: '1.0.0',
    keywords: ['开关', '切换', '选择'],
    aliases: ['开关'],
    difficulty: 'beginner',
    popularity: 8,
    props: [
      {
        name: 'checked',
        type: 'boolean',
        description: '是否开启',
        required: false,
        default: false,
      },
      {
        name: 'disabled',
        type: 'boolean',
        description: '是否禁用',
        required: false,
        default: false,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          width: 'auto',
          height: 'auto',
          margin: '0',
        },
      },
    ],
  },
  {
    id: 'form',
    title: '表单',
    description: '表单容器组件',
    category: 'form',
    version: '1.0.0',
    keywords: ['表单', '容器', '输入'],
    aliases: ['表单'],
    difficulty: 'intermediate',
    popularity: 9,
    props: [
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: 'transparent',
          width: '100%',
          height: 'auto',
          padding: '16px',
          margin: '0',
          borderRadius: '0',
        },
      },
    ],
  },
  {
    id: 'search-box',
    title: '搜索框',
    description: '搜索输入框组件',
    category: 'form',
    version: '1.0.0',
    keywords: ['搜索', '输入框'],
    aliases: ['搜索框'],
    difficulty: 'beginner',
    popularity: 8,
    props: [
      {
        name: 'placeholder',
        type: 'string',
        description: '占位提示文字',
        required: false,
        default: '请输入搜索内容',
      },
      {
        name: 'value',
        type: 'string',
        description: '搜索框值',
        required: false,
        default: '',
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#f3f4f6',
          color: '#333333',
          fontSize: '14px',
          width: '100%',
          height: 'auto',
          padding: '8px 12px',
          margin: '0',
          borderRadius: '4px',
          borderColor: 'transparent',
          borderWidth: '1px',
          borderStyle: 'solid',
        },
      },
    ],
  },
  // 展示分类
  {
    id: 'avatar',
    title: '头像',
    description: '用户头像展示组件',
    category: 'display',
    version: '1.0.0',
    keywords: ['头像', '用户', '图片'],
    aliases: ['头像'],
    difficulty: 'beginner',
    popularity: 9,
    props: [
      {
        name: 'src',
        type: 'string',
        description: '头像图片地址',
        required: false,
        default: '',
      },
      {
        name: 'text',
        type: 'string',
        description: '头像文字',
        required: false,
        default: '',
      },
      {
        name: 'shape',
        type: 'string',
        description: '头像形状',
        required: false,
        default: 'circle',
        options: ['circle', 'square'],
      },
      {
        name: 'size',
        type: 'string|number',
        description: '头像大小',
        required: false,
        default: 48,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          margin: '0',
        },
      },
    ],
  },
  {
    id: 'icon',
    title: '图标',
    description: '图标组件',
    category: 'display',
    version: '1.0.0',
    keywords: ['图标', 'icon'],
    aliases: ['图标'],
    difficulty: 'beginner',
    popularity: 9,
    props: [
      {
        name: 'name',
        type: 'string',
        description: '图标名称',
        required: false,
        default: '',
      },
      {
        name: 'size',
        type: 'string|number',
        description: '图标大小',
        required: false,
        default: 20,
      },
      {
        name: 'color',
        type: 'string',
        description: '图标颜色',
        required: false,
        default: null,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          margin: '0',
        },
      },
    ],
  },
  {
    id: 'tag',
    title: '标签',
    description: '标签展示组件',
    category: 'display',
    version: '1.0.0',
    keywords: ['标签', '标记'],
    aliases: ['标签'],
    difficulty: 'beginner',
    popularity: 7,
    props: [
      {
        name: 'text',
        type: 'string',
        description: '标签文字',
        required: false,
        default: '',
      },
      {
        name: 'type',
        type: 'string',
        description: '标签类型',
        required: false,
        default: 'primary',
        options: ['primary', 'success', 'warning', 'danger', 'info'],
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          fontSize: '14px',
          padding: '2px 8px',
          margin: '0',
          borderRadius: '4px',
        },
      },
    ],
  },
  {
    id: 'empty',
    title: '空状态',
    description: '空状态展示组件',
    category: 'display',
    version: '1.0.0',
    keywords: ['空状态', '空', '占位'],
    aliases: ['空状态'],
    difficulty: 'beginner',
    popularity: 7,
    props: [
      {
        name: 'title',
        type: 'string',
        description: '空状态标题',
        required: false,
        default: '暂无数据',
      },
      {
        name: 'image',
        type: 'string',
        description: '空状态图片',
        required: false,
        default: null,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: 'transparent',
          padding: '20px',
          margin: '0',
          width: '100%',
          height: '200px',
        },
      },
    ],
  },
  // 反馈分类
  {
    id: 'badge',
    title: '徽标',
    description: '用于展示数字或文字状态的徽标组件，通常用作消息提醒',
    category: 'feedback',
    version: '1.0.0',
    keywords: ['徽标', '小红点', '通知', '计数'],
    aliases: ['徽标', '角标'],
    difficulty: 'beginner',
    popularity: 9,
    props: [
      {
        name: 'value',
        type: 'string|number',
        description: '徽标内容',
        required: false,
        default: null,
      },
      {
        name: 'max',
        type: 'string|number',
        description: '徽标内容最大值',
        required: false,
        default: null,
      },
      {
        name: 'type',
        type: 'string',
        description: '徽标颜色类型',
        required: false,
        default: 'primary',
        options: ['primary', 'success', 'warning', 'danger', 'info'],
      },
      {
        name: 'dot',
        type: 'boolean',
        description: '是否显示点徽标',
        required: false,
        default: false,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          fontSize: '12px',
          padding: '2px 6px',
          margin: '0',
          borderRadius: '10px',
        },
      },
    ],
  },
  {
    id: 'loading',
    title: '加载',
    description: '加载提示组件',
    category: 'feedback',
    version: '1.0.0',
    keywords: ['加载', 'loading', '提示'],
    aliases: ['加载'],
    difficulty: 'beginner',
    popularity: 9,
    props: [
      {
        name: 'text',
        type: 'string',
        description: '加载文字',
        required: false,
        default: '加载中...',
      },
      {
        name: 'type',
        type: 'string',
        description: '加载类型',
        required: false,
        default: 'spinner',
        options: ['spinner', 'circular'],
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          color: '#3b82f6',
          backgroundColor: 'transparent',
          padding: '10px',
          margin: '0',
        },
      },
    ],
  },
  {
    id: 'modal',
    title: '模态框',
    description: '弹出模态框组件',
    category: 'feedback',
    version: '1.0.0',
    keywords: ['模态框', '弹窗', '弹出'],
    aliases: ['模态框', '弹窗'],
    difficulty: 'intermediate',
    popularity: 8,
    props: [
      {
        name: 'visible',
        type: 'boolean',
        description: '是否显示',
        required: false,
        default: false,
      },
      {
        name: 'title',
        type: 'string',
        description: '模态框标题',
        required: false,
        default: '',
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#ffffff',
          borderRadius: '8px',
          padding: '16px',
        },
      },
    ],
  },
  {
    id: 'circle-progress',
    title: '圆形进度条',
    description: '圆形进度展示组件',
    category: 'feedback',
    version: '1.0.0',
    keywords: ['进度', '圆形', '进度条'],
    aliases: ['圆形进度'],
    difficulty: 'intermediate',
    popularity: 7,
    props: [
      {
        name: 'value',
        type: 'number',
        description: '当前进度值 0-100',
        required: false,
        default: 0,
      },
      {
        name: 'width',
        type: 'number',
        description: '圆环宽度',
        required: false,
        default: 4,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          color: '#3b82f6',
          width: '100px',
          height: '100px',
          margin: '0',
        },
      },
    ],
  },
  {
    id: 'line-progress',
    title: '线形进度条',
    description: '水平进度条组件',
    category: 'feedback',
    version: '1.0.0',
    keywords: ['进度', '线形', '进度条'],
    aliases: ['线形进度'],
    difficulty: 'beginner',
    popularity: 7,
    props: [
      {
        name: 'value',
        type: 'number',
        description: '当前进度值 0-100',
        required: false,
        default: 0,
      },
      {
        name: 'height',
        type: 'number',
        description: '进度条高度',
        required: false,
        default: 4,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#e5e7eb',
          color: '#3b82f6',
          borderRadius: '2px',
          width: '100%',
          margin: '0',
        },
      },
    ],
  },
  {
    id: 'loadmore',
    title: '加载更多',
    description: '加载更多提示组件',
    category: 'feedback',
    version: '1.0.0',
    keywords: ['加载', '更多', '分页'],
    aliases: ['加载更多'],
    difficulty: 'intermediate',
    popularity: 8,
    props: [
      {
        name: 'status',
        type: 'string',
        description: '加载状态',
        required: false,
        default: 'more',
        options: ['more', 'loading', 'no-more'],
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          color: '#666666',
          fontSize: '14px',
          padding: '10px',
          margin: '0',
        },
      },
    ],
  },
  // 容器分类
  {
    id: 'collapse',
    title: '折叠面板',
    description: '可折叠的内容面板组件',
    category: 'container',
    version: '1.0.0',
    keywords: ['折叠', '面板', '手风琴'],
    aliases: ['折叠面板'],
    difficulty: 'intermediate',
    popularity: 7,
    props: [
      {
        name: 'accordion',
        type: 'boolean',
        description: '是否手风琴模式',
        required: false,
        default: false,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#ffffff',
          borderRadius: '4px',
          borderColor: '#e5e7eb',
          borderWidth: '1px',
          borderStyle: 'solid',
          margin: '0',
          padding: '0',
          width: '100%',
        },
      },
    ],
  },
  {
    id: 'swiper',
    title: '轮播',
    description: '轮播图组件',
    category: 'container',
    version: '1.0.0',
    keywords: ['轮播', '滑动', 'banner'],
    aliases: ['轮播图'],
    difficulty: 'intermediate',
    popularity: 9,
    props: [
      {
        name: 'autoplay',
        type: 'boolean',
        description: '是否自动播放',
        required: false,
        default: true,
      },
      {
        name: 'interval',
        type: 'number',
        description: '自动播放间隔',
        required: false,
        default: 3000,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          borderRadius: '8px',
          overflow: 'hidden',
          width: '100%',
          height: '200px',
          margin: '0',
        },
      },
    ],
  },
  {
    id: 'popup',
    title: '弹出层',
    description: '弹出层容器组件',
    category: 'container',
    version: '1.0.0',
    keywords: ['弹出', '层', '容器'],
    aliases: ['弹出层'],
    difficulty: 'intermediate',
    popularity: 8,
    props: [
      {
        name: 'visible',
        type: 'boolean',
        description: '是否显示',
        required: false,
        default: false,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#ffffff',
          borderRadius: '16px 16px 0 0',
          padding: '16px',
        },
      },
    ],
  },
  {
    id: 'list',
    title: '列表',
    description: '列表容器组件',
    category: 'container',
    version: '1.0.0',
    keywords: ['列表', '容器'],
    aliases: ['列表'],
    difficulty: 'beginner',
    popularity: 7,
    props: [
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#ffffff',
          borderRadius: '8px',
          padding: '0',
          margin: '0',
          width: '100%',
        },
      },
    ],
  },
  {
    id: 'sticky',
    title: '吸顶',
    description: '吸顶容器组件',
    category: 'container',
    version: '1.0.0',
    keywords: ['吸顶', '固定', '粘性'],
    aliases: ['吸顶'],
    difficulty: 'intermediate',
    popularity: 7,
    props: [
      {
        name: 'offsetTop',
        type: 'number',
        description: '顶部偏移量',
        required: false,
        default: 0,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#ffffff',
          width: '100%',
          padding: '0',
          margin: '0',
        },
      },
    ],
  },
  // 业务分类
  {
    id: 'calendar',
    title: '日历',
    description: '日历选择组件',
    category: 'business',
    version: '1.0.0',
    keywords: ['日历', '日期', '选择'],
    aliases: ['日历'],
    difficulty: 'advanced',
    popularity: 8,
    props: [
      {
        name: 'date',
        type: 'string',
        description: '当前选中日期',
        required: false,
        default: '',
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#ffffff',
          borderRadius: '8px',
          padding: '12px',
          width: '100%',
          margin: '0',
        },
      },
    ],
  },
  {
    id: 'count-down',
    title: '倒计时',
    description: '倒计时组件',
    category: 'business',
    version: '1.0.0',
    keywords: ['倒计时', '定时器', '时间'],
    aliases: ['倒计时'],
    difficulty: 'intermediate',
    popularity: 7,
    props: [
      {
        name: 'time',
        type: 'number',
        description: '倒计时时间（秒）',
        required: false,
        default: 60,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          color: '#333333',
          fontSize: '14px',
          backgroundColor: '#f3f4f6',
          padding: '8px 12px',
          borderRadius: '4px',
        },
      },
    ],
  },
  {
    id: 'rate',
    title: '评分',
    description: '评分组件',
    category: 'business',
    version: '1.0.0',
    keywords: ['评分', '打分', '评价'],
    aliases: ['评分'],
    difficulty: 'intermediate',
    popularity: 7,
    props: [
      {
        name: 'value',
        type: 'number',
        description: '当前评分',
        required: false,
        default: 0,
      },
      {
        name: 'max',
        type: 'number',
        description: '最大评分',
        required: false,
        default: 5,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          margin: '0',
          gap: '4px',
        },
      },
    ],
  },
  {
    id: 'image-upload',
    title: '图片上传',
    description: '图片上传选择组件',
    category: 'business',
    version: '1.0.0',
    keywords: ['图片', '上传', '选择'],
    aliases: ['图片上传'],
    difficulty: 'intermediate',
    popularity: 8,
    props: [
      {
        name: 'count',
        type: 'number',
        description: '最大选择数量',
        required: false,
        default: 9,
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          width: '100%',
          margin: '0',
        },
      },
    ],
  },
  // 其他分类
  {
    id: 'notice-bar',
    title: '通知栏',
    description: '通知提示栏组件',
    category: 'other',
    version: '1.0.0',
    keywords: ['通知', '提示', '公告'],
    aliases: ['通知栏'],
    difficulty: 'beginner',
    popularity: 8,
    props: [
      {
        name: 'text',
        type: 'string',
        description: '通知文字',
        required: false,
        default: '',
      },
      {
        name: 'mode',
        type: 'string',
        description: '显示模式',
        required: false,
        default: 'closed',
        options: ['closed', 'linkable'],
      },
      {
        name: 'style',
        type: 'object',
        description: '自定义样式',
        required: false,
        default: {
          backgroundColor: '#fffbeb',
          color: '#d97706',
          borderRadius: '4px',
          padding: '8px 12px',
        },
      },
    ],
  },
]

// 获取分类映射
export const getCategoryMap = () => {
  const map: Record<string, BaseCategory> = {}
  baseCategories.forEach((cat) => {
    map[cat.id] = cat
  })
  return map
}

// 获取组件映射
export const getComponentMap = () => {
  const map: Record<string, BaseComponentMeta> = {}
  baseComponents.forEach((comp) => {
    map[comp.id] = comp
  })
  return map
}
